- kind: helm
  repository: https://argoproj.github.io/argo-helm
  chart: argo-cd
  values: |
    crds:
      install: true
- kind: helm
  repository: https://argoproj.github.io/argo-helm
  chart: argo-workflows
  values: |
    crds:
      install: true
    server:
      clusterWorkflowTemplates:
        enabled: true
- kind: git
  repository: https://github.com/dexidp/dex.git
  path: scripts/manifests/crds
  revision: master
- kind: git
  repository: https://github.com/aws/eks-charts.git
  path: stable/aws-load-balancer-controller/crds
  revision: master
- kind: git
  repository: https://github.com/aws/eks-charts.git
  path: stable/aws-vpc-cni/crds
  revision: master
- kind: helm
  repository: https://charts.external-secrets.io
  chart: external-secrets
  values: |
    installCRDs: true
- kind: helm
  repository: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  values: |
    crds:
      enabled: true
